# REPOSITORY
spring.application.name=dirmon
spring.application.description=A Spring Boot application that monitors user-defined directories in real time, detecting file creation, deletion, and modifications instantly.
spring.application.version=1.0.0

# APPLICATION
server.port=8080
management.endpoints.web.exposure.include=health
management.endpoint.health.show-details=always
management.health.diskspace.enabled=false
management.health.ssl.enabled=false
management.health.rabbit.enabled=false
management.health.redis.enabled=false
management.health.mongo.enabled=false
management.health.cassandra.enabled=false
management.health.solr.enabled=false
management.health.ping.enabled=true
management.health.db.enabled=false

# DATABASE
spring.datasource.driver-class-name=org.postgresql.Driver
spring.datasource.url=jdbc:postgresql://database:5432/${POSTGRES_DB}
spring.datasource.username=${POSTGRES_USER}
spring.datasource.password=${POSTGRES_PASSWORD}
spring.jpa.database-platform=postgres
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=false

logging.level.org.hibernate.SQL=OFF
logging.level.org.hibernate.type.descriptor.sql.BasicBinder=OFF
logging.level.org.hibernate.engine.jdbc.spi.SqlStatementLogger=OFF

# EXTERNAL
frontend.base_url=http://localhost:3000

# SECURITY
spring.security.token.auth.secret=${SPRING_SECURITY_AUTH_TOKEN_SECRET}
spring.security.token.access.expiration=900000
spring.security.token.refresh.expiration=2592000000

spring.security.token.agent.secret=${SPRING_SECURITY_AGENT_TOKEN_SECRET}
spring.security.token.agent.activation.expiration=60000
spring.security.token.agent.heartbeat.expiration=15000

spring.security.user.name=${SPRING_SECURITY_USER_NAME}
spring.security.user.password=${SPRING_SECURITY_USER_PASSWORD}
spring.security.user.roles=${SPRING_SECURITY_USER_ROLES}

# SCHEDULING TASKS
agent.scheduler.offline-threshold.interval=15000
user.scheduler.deletion-threshold.interval=7776000000
